cloud:
  aws:
    region:
      static: us-east-1
      auto: false

    credentials:
      access-key: AKIASWXDDHB4FIY6KQUP
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/186233600120/booking

sentry:
  dns: https://756529db8f0243a595843a808d5561e7@o1099686.ingest.sentry.io/6124452

spring:
  datasource:
    url: jdbc:mysql://lean-tech-hotel.ct9njye4wmlr.us-east-1.rds.amazonaws.com:3306/sys
    username: admin
    password: a1234567

    hikari:
      connection-timeout: 20000
      connection-test-query: SELECT 1 FROM dual;
      minimum-idle: 1
      maximum-pool-size: 5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8081