cloud:
  aws:
    region:
      static: us-east-1
      auto: false

    credentials:
      access-key: AKIASWXDDHB4FIY6KQUP
      secret-key: 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
    booking-queue:
      end-point:
        uri: https://sqs.us-east-1.amazonaws.com/186233600120/booking
      name: booking
    mail-from: danielmartinezg95@gmail.com
    default-mail-to: danielmartinezg95@gmail.com

sentry:
  dns: https://756529db8f0243a595843a808d5561e7@o1099686.ingest.sentry.io/6124452

spring:
  datasource:
    url: jdbc:mysql://lean-tech-hotel.ct9njye4wmlr.us-east-1.rds.amazonaws.com:3306/sys
    username: admin
    password: a1234567

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8082
